### ISSUE TITLE
Please keep me updated 

### ISSUE THREAD

**Issue by tusharchou** [redpheonixx/Trading_Company_Data_Platorm#6]
![Screenshot_20240901-130130.png](https://github.com/user-attachments/assets/6240b828-08e0-460e-a0c4-ed5b4569fcb9)

**Comment by tusharchou** [comment]
Hi Amit, 

Hope you are doing well.

I am writing to you because i believe in your success and would want to encourage you to see this through. All the best!

Remember to relax and have a good Sunday 😁 

Cheers

**Comment by tusharchou** [comment]
Hi @redpheonixx ,

I am having a good productive spell. How are you?

Can you please share some visibility on your progress, is there any pull request you would want me to review?

Cheers 
Tushar

**Comment by redpheonixx** [comment]
updated readme with milestones.
please keep checking it for progress
